sentiment-classification:
  category: nlu
  primary_metric: mcc
  secondary_metric: macro_f1

named-entity-recognition:
  category: nlu
  primary_metric: micro_f1_no_misc
  secondary_metric: micro_f1

linguistic-acceptability:
  category: nlu
  primary_metric: mcc
  secondary_metric: macro_f1

reading-comprehension:
  category: nlu
  primary_metric: f1
  secondary_metric: em

knowledge:
  category: nlg
  primary_metric: mcc
  secondary_metric: accuracy

common-sense-reasoning:
  category: nlg
  primary_metric: mcc
  secondary_metric: accuracy

summarization:
  category: nlg
  primary_metric: bertscore
  secondary_metric: rouge_l

speed:
  category: null
  primary_metric: speed
  secondary_metric: speed_short
